const ConstantImages = {
  fb: require('../../../assets/fb.png'),
  bg: require('../../../assets/bg.png'),
  logo: require('../../../assets/H.png'),
  view: require('../../../assets/view.png'),
  back: require('../../../assets/back.png'),
  hide: require('../../../assets/hide.png'),
  goggle: require('../../../assets/goggle.png'),
  twitter: require('../../../assets/twitter.png'),
  checkBox: require('../../../assets/checkBox.png'),
  coffeeBG: require('../../../assets/coffeeBG.png'),
  blackBG: require('../../../assets/blackBG.png'),
  lady: require('../../../assets/lady.png'),
  star: require('../../../assets/star.png'),
  filterIcon: require('../../../assets/filterIcon.png'),
  price: require('../../../assets/price.png'),
  search: require('../../../assets/search.png'),
  coffee1: require('../../../assets/coffee1.png'),
  coffee2: require('../../../assets/coffee2.png'),
  whiteLogo: require('../../../assets/whiteLogo.png'),
  downArrow: require('../../../assets/downArrow.png'),
  blankCheckBox: require('../../../assets/blankCheckBox.png'),
  backgroundImage: require('../../../assets/backgroundImage.png'),
  home: require('../../../assets/Home.png'),
  bag: require('../../../assets/bag.png'),
  Notification: require('../../../assets/Notification.png'),
  heart: require('../../../assets/Heart.png'),
};

export default ConstantImages;
